"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from slackwebapi.apis.admin_apps_api import (
    AdminAppsApi,
)
from slackwebapi.apis.admin_apps_approved_api import (
    AdminAppsApprovedApi,
)
from slackwebapi.apis.admin_apps_requests_api import (
    AdminAppsRequestsApi,
)
from slackwebapi.apis.admin_apps_restricted_api import (
    AdminAppsRestrictedApi,
)
from slackwebapi.apis.admin_conversations_api import (
    AdminConversationsApi,
)
from slackwebapi.apis.admin_conversations_ekm_api import (
    AdminConversationsEkmApi,
)
from slackwebapi.apis.admin_conversations_restrict_access_api import (
    AdminConversationsRestrictAccessApi,
)
from slackwebapi.apis.admin_emoji_api import (
    AdminEmojiApi,
)
from slackwebapi.apis.admin_invite_requests_api import (
    AdminInviteRequestsApi,
)
from slackwebapi.apis.admin_invite_requests_approved_api import (
    AdminInviteRequestsApprovedApi,
)
from slackwebapi.apis.admin_invite_requests_denied_api import (
    AdminInviteRequestsDeniedApi,
)
from slackwebapi.apis.admin_teams_admins_api import (
    AdminTeamsAdminsApi,
)
from slackwebapi.apis.admin_teams_api import (
    AdminTeamsApi,
)
from slackwebapi.apis.admin_teams_owners_api import (
    AdminTeamsOwnersApi,
)
from slackwebapi.apis.admin_teams_settings_api import (
    AdminTeamsSettingsApi,
)
from slackwebapi.apis.admin_usergroups_api import (
    AdminUsergroupsApi,
)
from slackwebapi.apis.admin_users_api import (
    AdminUsersApi,
)
from slackwebapi.apis.admin_users_session_api import (
    AdminUsersSessionApi,
)
from slackwebapi.apis.api import Api
from slackwebapi.apis.apps_api import AppsApi
from slackwebapi.apis.apps_event_authorizations_api import (
    AppsEventAuthorizationsApi,
)
from slackwebapi.apis.apps_permissions_api import (
    AppsPermissionsApi,
)
from slackwebapi.apis.apps_permissions_resources_api import (
    AppsPermissionsResourcesApi,
)
from slackwebapi.apis.apps_permissions_scopes_api import (
    AppsPermissionsScopesApi,
)
from slackwebapi.apis.apps_permissions_users_api import (
    AppsPermissionsUsersApi,
)
from slackwebapi.apis.auth_api import AuthApi
from slackwebapi.apis.base_api import BaseApi
from slackwebapi.apis.bots_api import BotsApi
from slackwebapi.apis.calls_api import CallsApi
from slackwebapi.apis.calls_participants_api import (
    CallsParticipantsApi,
)
from slackwebapi.apis.chat_api import ChatApi
from slackwebapi.apis.chat_scheduled_messages_api import (
    ChatScheduledMessagesApi,
)
from slackwebapi.apis.conversations_api import (
    ConversationsApi,
)
from slackwebapi.apis.dialog_api import DialogApi
from slackwebapi.apis.dnd_api import DndApi
from slackwebapi.apis.emoji_api import EmojiApi
from slackwebapi.apis.files_api import FilesApi
from slackwebapi.apis.files_comments_api import (
    FilesCommentsApi,
)
from slackwebapi.apis.files_remote_api import (
    FilesRemoteApi,
)
from slackwebapi.apis.migration_api import MigrationApi
from slackwebapi.apis.oauth_api import OauthApi
from slackwebapi.apis.oauth_authorization_api import (
    OauthAuthorizationApi,
)
from slackwebapi.apis.oauth_v_2_api import OauthV2Api
from slackwebapi.apis.pins_api import PinsApi
from slackwebapi.apis.reactions_api import ReactionsApi
from slackwebapi.apis.reminders_api import RemindersApi
from slackwebapi.apis.rtm_api import RtmApi
from slackwebapi.apis.search_api import SearchApi
from slackwebapi.apis.stars_api import StarsApi
from slackwebapi.apis.team_api import TeamApi
from slackwebapi.apis.team_profile_api import (
    TeamProfileApi,
)
from slackwebapi.apis.usergroups_api import (
    UsergroupsApi,
)
from slackwebapi.apis.usergroups_users_api import (
    UsergroupsUsersApi,
)
from slackwebapi.apis.users_api import UsersApi
from slackwebapi.apis.users_profile_api import (
    UsersProfileApi,
)
from slackwebapi.apis.views_api import ViewsApi
from slackwebapi.apis.workflows_api import WorkflowsApi
from slackwebapi.configuration import (
    Configuration,
    Environment,
)
from slackwebapi.http.auth.oauth_2 import Oauth2


class SlackwebapiClient(object):
    """Client that provide access to the SlackwebapiClient APIs."""

    @LazyProperty
    def admin_apps(self):
        """Provide access to the AdminAppsApi endpoints."""
        return AdminAppsApi(self.global_configuration)

    @LazyProperty
    def admin_apps_approved(self):
        """Provide access to the AdminAppsApprovedApi endpoints."""
        return AdminAppsApprovedApi(self.global_configuration)

    @LazyProperty
    def admin_apps_requests(self):
        """Provide access to the AdminAppsRequestsApi endpoints."""
        return AdminAppsRequestsApi(self.global_configuration)

    @LazyProperty
    def admin_apps_restricted(self):
        """Provide access to the AdminAppsRestrictedApi endpoints."""
        return AdminAppsRestrictedApi(self.global_configuration)

    @LazyProperty
    def admin_conversations(self):
        """Provide access to the AdminConversationsApi endpoints."""
        return AdminConversationsApi(self.global_configuration)

    @LazyProperty
    def admin_conversations_ekm(self):
        """Provide access to the AdminConversationsEkmApi endpoints."""
        return AdminConversationsEkmApi(self.global_configuration)

    @LazyProperty
    def admin_conversations_restrict_access(self):
        """Provide access to the AdminConversationsRestrictAccessApi endpoints."""
        return AdminConversationsRestrictAccessApi(self.global_configuration)

    @LazyProperty
    def admin_emoji(self):
        """Provide access to the AdminEmojiApi endpoints."""
        return AdminEmojiApi(self.global_configuration)

    @LazyProperty
    def admin_invite_requests(self):
        """Provide access to the AdminInviteRequestsApi endpoints."""
        return AdminInviteRequestsApi(self.global_configuration)

    @LazyProperty
    def admin_invite_requests_approved(self):
        """Provide access to the AdminInviteRequestsApprovedApi endpoints."""
        return AdminInviteRequestsApprovedApi(self.global_configuration)

    @LazyProperty
    def admin_invite_requests_denied(self):
        """Provide access to the AdminInviteRequestsDeniedApi endpoints."""
        return AdminInviteRequestsDeniedApi(self.global_configuration)

    @LazyProperty
    def admin_teams_admins(self):
        """Provide access to the AdminTeamsAdminsApi endpoints."""
        return AdminTeamsAdminsApi(self.global_configuration)

    @LazyProperty
    def admin_teams(self):
        """Provide access to the AdminTeamsApi endpoints."""
        return AdminTeamsApi(self.global_configuration)

    @LazyProperty
    def admin_teams_owners(self):
        """Provide access to the AdminTeamsOwnersApi endpoints."""
        return AdminTeamsOwnersApi(self.global_configuration)

    @LazyProperty
    def admin_teams_settings(self):
        """Provide access to the AdminTeamsSettingsApi endpoints."""
        return AdminTeamsSettingsApi(self.global_configuration)

    @LazyProperty
    def admin_usergroups(self):
        """Provide access to the AdminUsergroupsApi endpoints."""
        return AdminUsergroupsApi(self.global_configuration)

    @LazyProperty
    def admin_users(self):
        """Provide access to the AdminUsersApi endpoints."""
        return AdminUsersApi(self.global_configuration)

    @LazyProperty
    def admin_users_session(self):
        """Provide access to the AdminUsersSessionApi endpoints."""
        return AdminUsersSessionApi(self.global_configuration)

    @LazyProperty
    def api(self):
        """Provide access to the Api endpoints."""
        return Api(self.global_configuration)

    @LazyProperty
    def apps_event_authorizations(self):
        """Provide access to the AppsEventAuthorizationsApi endpoints."""
        return AppsEventAuthorizationsApi(self.global_configuration)

    @LazyProperty
    def apps_permissions(self):
        """Provide access to the AppsPermissionsApi endpoints."""
        return AppsPermissionsApi(self.global_configuration)

    @LazyProperty
    def apps_permissions_resources(self):
        """Provide access to the AppsPermissionsResourcesApi endpoints."""
        return AppsPermissionsResourcesApi(self.global_configuration)

    @LazyProperty
    def apps_permissions_scopes(self):
        """Provide access to the AppsPermissionsScopesApi endpoints."""
        return AppsPermissionsScopesApi(self.global_configuration)

    @LazyProperty
    def apps_permissions_users(self):
        """Provide access to the AppsPermissionsUsersApi endpoints."""
        return AppsPermissionsUsersApi(self.global_configuration)

    @LazyProperty
    def apps(self):
        """Provide access to the AppsApi endpoints."""
        return AppsApi(self.global_configuration)

    @LazyProperty
    def auth(self):
        """Provide access to the AuthApi endpoints."""
        return AuthApi(self.global_configuration)

    @LazyProperty
    def bots(self):
        """Provide access to the BotsApi endpoints."""
        return BotsApi(self.global_configuration)

    @LazyProperty
    def calls(self):
        """Provide access to the CallsApi endpoints."""
        return CallsApi(self.global_configuration)

    @LazyProperty
    def calls_participants(self):
        """Provide access to the CallsParticipantsApi endpoints."""
        return CallsParticipantsApi(self.global_configuration)

    @LazyProperty
    def chat(self):
        """Provide access to the ChatApi endpoints."""
        return ChatApi(self.global_configuration)

    @LazyProperty
    def chat_scheduled_messages(self):
        """Provide access to the ChatScheduledMessagesApi endpoints."""
        return ChatScheduledMessagesApi(self.global_configuration)

    @LazyProperty
    def conversations(self):
        """Provide access to the ConversationsApi endpoints."""
        return ConversationsApi(self.global_configuration)

    @LazyProperty
    def dialog(self):
        """Provide access to the DialogApi endpoints."""
        return DialogApi(self.global_configuration)

    @LazyProperty
    def dnd(self):
        """Provide access to the DndApi endpoints."""
        return DndApi(self.global_configuration)

    @LazyProperty
    def emoji(self):
        """Provide access to the EmojiApi endpoints."""
        return EmojiApi(self.global_configuration)

    @LazyProperty
    def files_comments(self):
        """Provide access to the FilesCommentsApi endpoints."""
        return FilesCommentsApi(self.global_configuration)

    @LazyProperty
    def files(self):
        """Provide access to the FilesApi endpoints."""
        return FilesApi(self.global_configuration)

    @LazyProperty
    def files_remote(self):
        """Provide access to the FilesRemoteApi endpoints."""
        return FilesRemoteApi(self.global_configuration)

    @LazyProperty
    def migration(self):
        """Provide access to the MigrationApi endpoints."""
        return MigrationApi(self.global_configuration)

    @LazyProperty
    def oauth(self):
        """Provide access to the OauthApi endpoints."""
        return OauthApi(self.global_configuration)

    @LazyProperty
    def oauth_v_2(self):
        """Provide access to the OauthV2Api endpoints."""
        return OauthV2Api(self.global_configuration)

    @LazyProperty
    def pins(self):
        """Provide access to the PinsApi endpoints."""
        return PinsApi(self.global_configuration)

    @LazyProperty
    def reactions(self):
        """Provide access to the ReactionsApi endpoints."""
        return ReactionsApi(self.global_configuration)

    @LazyProperty
    def reminders(self):
        """Provide access to the RemindersApi endpoints."""
        return RemindersApi(self.global_configuration)

    @LazyProperty
    def rtm(self):
        """Provide access to the RtmApi endpoints."""
        return RtmApi(self.global_configuration)

    @LazyProperty
    def search(self):
        """Provide access to the SearchApi endpoints."""
        return SearchApi(self.global_configuration)

    @LazyProperty
    def stars(self):
        """Provide access to the StarsApi endpoints."""
        return StarsApi(self.global_configuration)

    @LazyProperty
    def team(self):
        """Provide access to the TeamApi endpoints."""
        return TeamApi(self.global_configuration)

    @LazyProperty
    def team_profile(self):
        """Provide access to the TeamProfileApi endpoints."""
        return TeamProfileApi(self.global_configuration)

    @LazyProperty
    def usergroups(self):
        """Provide access to the UsergroupsApi endpoints."""
        return UsergroupsApi(self.global_configuration)

    @LazyProperty
    def usergroups_users(self):
        """Provide access to the UsergroupsUsersApi endpoints."""
        return UsergroupsUsersApi(self.global_configuration)

    @LazyProperty
    def users(self):
        """Provide access to the UsersApi endpoints."""
        return UsersApi(self.global_configuration)

    @LazyProperty
    def users_profile(self):
        """Provide access to the UsersProfileApi endpoints."""
        return UsersProfileApi(self.global_configuration)

    @LazyProperty
    def views(self):
        """Provide access to the ViewsApi endpoints."""
        return ViewsApi(self.global_configuration)

    @LazyProperty
    def workflows(self):
        """Provide access to the WorkflowsApi endpoints."""
        return WorkflowsApi(self.global_configuration)

    @LazyProperty
    def oauth_authorization(self):
        """Provide access to the OauthAuthorizationApi endpoints."""
        return OauthAuthorizationApi(self.global_configuration)

    @property
    def slack_auth(self):
        """Provide access to the SlackAuth auth manager."""
        return self.auth_managers["slackAuth"]

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 authorization_code_auth_credentials=None, config=None):
        """Initialize a new instance of SlackwebapiClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            authorization_code_auth_credentials=authorization_code_auth_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

        self.auth_managers = {
            "slackAuth": Oauth2(self.config.authorization_code_auth_credentials,
                                self.global_configuration),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            SlackwebapiClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
